### ISSUE TITLE
v4.1 PC & Mobile - when there is an email address, enable click to prompt to email person

### ISSUE THREAD

**Issue by rmcallister** [harryvok/Merit.PHP.Traveller.Repository#219]

**Comment by jamesMerit** [comment]
Default email client needs to be setup - otherwise "mailto:" links won't work.

To do this on windows 8:
1. Press start key
2. Type "Default Programs"
3. Press Enter
4. Select option 1 or "Set your Default Programs"
5. Select "Outlook(Desktop)" or preferred mail program.
6. Select "Set this program as default"

Mailto: links should now open a new window of mail program with the "to:" field filled out.

**Comment by rmcallister** [comment]
fixed

**Comment by rmcallister** [comment]
im sorry Jo reminded me that this feature will mean the email wont be recorded in notifications tab so can we please hide this functionality until we can prompt the email to open the notifications window with this email placed into send to field. phone is fine

**Comment by jamesMerit** [comment]
removed
